db_files = [
    "test2.db",
    # "A1_commerce.db",
    # "A1_msgstore.db",
    # "A1_wa.db",
    # "A2_core.db",
    # "A2_journal.db",
    # "A2_main.db",
    # "A3_account1cache4.db",
    # "A3_account2cache4.db",
    # "A3_account3cache4.db",
    # "A4_gmm_myplaces.db",
    # "A4_gmm_storage.db",
    # "A4_peopleCache_sharononeil368@gmail.com_com.google_14.db",
    # "A5_SBrowser.db",
    # "A5_SBrowser2.db",
    # "A5_searchengine.db",
    # "I1_CallHistory.sqlite",
    # "I1_ChatStorage.sqlite",
    # "I1_ContactsV2.sqlite",
    # "I2_AddressBook.sqlitedb",
    # "I2_AddressBookImages.sqlitedb",
    # "I3_sms.db",
    # "I4_CloudTabs.db",
    # "I4_History.db",
    # "I5_Calendar.sqlitedb",
    # "I5_Extras.db",
]
